# Generated by Django 5.2.11 on 2026-02-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_embedded',
            field=models.BooleanField(default=False),
        ),
    ]
